### WELCOME MESSAGE CHECK TO SEE IF DATABASE IS SETUP
GET http://localhost:8080/api/info


##### ***USER ENDPOINTS*** #####

### SYSTEM GREETS USER IF LOGGED IN
#GET http://localhost:8080/api/info/user
#x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NjcyOTYyMTAsImlhdCI6MTY2NzI5NDQxMCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.dlsMNiQc_OYU2HCa-WMzNImQ3qoNy2CGXEWAbXBQM3g"

### GET ALL USERS
GET http://localhost:8080/api/users/all
Content-Type: application/json

### GET USER BY USERNAME
GET http://localhost:8080/api/users/marklundgaard
Content-Type: application/json

### CREATE USER
POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "userName": "lasse",
  "userEmail": "lasse@gmail.com",
  "userPass": "test123"
}

### UPDATE USER
PUT http://localhost:8080/api/users/lynper
Content-Type: application/json

{
  "userEmail": "lynerenper@gmail.com"
}

### DELETE USER
DELETE http://localhost:8080/api/users/lynper
Content-Type: application/json




##### ***BOAT ENDPOINTS*** #####

### GET ALL BOATS
GET http://localhost:8080/api/boats/all
Content-Type: application/json

### GET BOATS BY HARBOUR
GET http://localhost:8080/api/boats/Køge Marina
Content-Type: application/json

### CREATE BOAT
POST http://localhost:8080/api/boats
Content-Type: application/json

{
  "boatBrand": "TestBoat4",
  "boatMake": "T4",
  "boatName": "Testen4",
  "boatImage": "boattest4.png",
  "harbour": {
    "harbourID": 1
  }
}

### ASSIGN BOAT TO HARBOUR
POST http://localhost:8080/api/boats/assign/7/2
Content-Type: application/json

### UPDATE BOAT - virker kun inklusiv harbour.
PUT http://localhost:8080/api/boats/update/5
Content-Type: application/json

{
  "boatBrand": "Technomar",
  "boatMake": "Velvet 7",
  "boatName": "Bigboy",
  "boatImage": "bigboat.png",
  "harbour": {
    "harbourID": 1
  }
}

### DELETE BOAT
DELETE http://localhost:8080/api/boats/5
Content-Type: application/json




##### ***OWNER ENDPOINTS*** #####

### GET ALL OWNERS
GET http://localhost:8080/api/owners/all
Content-Type: application/json

### GET OWNERS BY BOAT
GET http://localhost:8080/api/owners/Fidos Båd
Content-Type: application/json




##### ***HARBOUR ENDPOINTS*** #####

### GET ALL HARBOURS
GET http://localhost:8080/api/harbours/all
Content-Type: application/json

### GET HARBOUR BY HARBOUR NAME
GET http://localhost:8080/api/owners/Fidos Båd
Content-Type: application/json




