### WELCOME MESSAGE CHECK TO SEE IF DATABASE IS SETUP
GET http://localhost:8080/api/info

##### USER ENDPOINTS #####

### SYSTEM GREETS USER IF LOGGED IN
#GET http://localhost:8080/api/info/user
#x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NjcyOTYyMTAsImlhdCI6MTY2NzI5NDQxMCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.dlsMNiQc_OYU2HCa-WMzNImQ3qoNy2CGXEWAbXBQM3g"

### GET ALL USERS

### GET USER BY USERNAME

### CREATE PERSON

### UPDATE USER

### DELETE USER

